pipeline {
	agent any
	tools {
		maven 'Maven-Vishal'
        sonarScanner 'sonar-Scanner' 
	}
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Code Analysis'){
            steps{
                bat 'sonar-scanner -Dsonar.projectKey=SimpleMaven -Dsonar.projectName=SimpleMaven  -Dsonar.projectVersion=1.0  -Dsonar.sources=. '
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}
