node {
	def mvnHome = tool 'Maven-Vishal'
    def sonarHome = tool 'sonar-Scanner'
    bat '${mvnHome}/bin/mvn -B -DskipTests clean '
    /*
    stage('Build') {
            bat '${mvnHome}/bin/mvn -B -DskipTests clean package'
            echo 'Build Success'
    }
    stage('Test') {
            bat '${mvnHome}/bin/mvn test'
            echo 'Test Success'
        
        }
    }
    stage('Code Analysis'){
            bat '${sonarHome}/sonar-scanner -Dsonar.projectKey=SimpleMaven -Dsonar.projectName=SimpleMaven  -Dsonar.projectVersion=1.0  -Dsonar.sources=. '
            echo 'Code Analysis Success'

    }
    stage('Deliver') {
            bat './jenkins/scripts/deliver.sh'
            echo 'Delivery Success'
    }*/
}
